# The way this is done is very WRONG.
# It is due to the unavailability of the CEML compiler source.
FROM ruby:3-buster AS RUN
LABEL maintainer=preston.lee@prestonlee.com

RUN mkdir /app
WORKDIR /app

# Install JRE
RUN apt search openjdk
RUN apt-get update && apt-get install -y openjdk-11-jre

# Install dependencies
COPY Gemfile .
RUN bundle install

# WRONG Copy in the compiler. :(
COPY ceml-3.0.4-jar-with-dependencies.jar .
COPY def .
COPY cem .
COPY fhir .
COPY app.rb .

EXPOSE 4567
CMD APP_ENV=production ruby app.rb
